// RECONSTRUCTED. Exact IL: reconstructed/evidence/CoordinatePicker.il.txt
using System; using System.Diagnostics; using System.Drawing;
namespace ModernAutoClicker.Reconstructed
{
    internal sealed class CoordinatePicker
    {
        private Color _currentColor=Color.Black; public bool IsAreaSelectionMode{get;set;} public event Action<Point> OnPointPicked; public event Action<Point,Color> OnPointAndColorPicked; public event Action<Point,Color,WindowTargetInfo,Point> OnPointSelectedWithWindow; public event Action<Point,Point,Color,WindowTargetInfo,Point,Point> OnAreaSelectedWithWindow;
        internal void ConfirmPoint(Point screenPoint){Color color=_currentColor==Color.Black?NativeMethods.GetPixelColorReference(screenPoint.X,screenPoint.Y):_currentColor;var np=new NativeMethods.POINT{X=screenPoint.X,Y=screenPoint.Y};IntPtr hwnd=NativeMethods.WindowFromPoint(np);if(hwnd!=IntPtr.Zero)hwnd=NativeMethods.GetTopLevelWindow(hwnd);WindowTargetInfo target=null;Point clientPoint=screenPoint;if(hwnd!=IntPtr.Zero){NativeMethods.GetWindowThreadProcessId(hwnd,out uint pid);if(pid!=(uint)Process.GetCurrentProcess().Id&&pid!=0){string proc="App";try{proc=Process.GetProcessById((int)pid).ProcessName;}catch{}string title=NativeMethods.ReadWindowTitleReference(hwnd).Trim();var cp=np;NativeMethods.ScreenToClient(hwnd,ref cp);clientPoint=new Point(cp.X,cp.Y);target=new WindowTargetInfo{Hwnd=hwnd,ProcessName=proc,Title=title};}}OnPointPicked?.Invoke(screenPoint);OnPointAndColorPicked?.Invoke(screenPoint,color);OnPointSelectedWithWindow?.Invoke(screenPoint,color,target,clientPoint);}
        internal void ConfirmArea(Point startScreen,Point endScreen){Color color=_currentColor==Color.Black?NativeMethods.GetPixelColorReference(endScreen.X,endScreen.Y):_currentColor;if(Math.Abs(endScreen.X-startScreen.X)<5&&Math.Abs(endScreen.Y-startScreen.Y)<5){startScreen=new Point(startScreen.X-25,startScreen.Y-25);endScreen=new Point(endScreen.X+25,endScreen.Y+25);}Point a=new Point(Math.Min(startScreen.X,endScreen.X),Math.Min(startScreen.Y,endScreen.Y)),b=new Point(Math.Max(startScreen.X,endScreen.X),Math.Max(startScreen.Y,endScreen.Y));var pa=new NativeMethods.POINT{X=a.X,Y=a.Y};var pb=new NativeMethods.POINT{X=b.X,Y=b.Y};IntPtr hwnd=NativeMethods.WindowFromPoint(pa);if(hwnd==IntPtr.Zero)hwnd=NativeMethods.WindowFromPoint(pb);if(hwnd!=IntPtr.Zero)hwnd=NativeMethods.GetTopLevelWindow(hwnd);WindowTargetInfo target=null;Point ca=a,cb=b;if(hwnd!=IntPtr.Zero){NativeMethods.GetWindowThreadProcessId(hwnd,out uint pid);if(pid!=(uint)Process.GetCurrentProcess().Id&&pid!=0){string proc="App";try{proc=Process.GetProcessById((int)pid).ProcessName;}catch{}target=new WindowTargetInfo{Hwnd=hwnd,ProcessName=proc,Title=NativeMethods.ReadWindowTitleReference(hwnd).Trim()};NativeMethods.ScreenToClient(hwnd,ref pa);NativeMethods.ScreenToClient(hwnd,ref pb);ca=new Point(pa.X,pa.Y);cb=new Point(pb.X,pb.Y);}}OnAreaSelectedWithWindow?.Invoke(a,b,color,target,ca,cb);}
    }
    internal sealed class WindowTargetInfo{public IntPtr Hwnd;public string ProcessName;public string Title;}
}
