// RECONSTRUCTED. Exact IL: reconstructed/evidence/KeyboardSimulator.il.txt
using System; using System.Collections.Generic; using System.Runtime.InteropServices; using System.Threading;
namespace ModernAutoClicker.Reconstructed
{
    internal static class KeyboardSimulator
    {
        internal static void ExecuteKeyPress(string expression,int holdMs){if(string.IsNullOrWhiteSpace(expression))return;string[] parts=expression.Split(new[]{'+','-',' '},StringSplitOptions.RemoveEmptyEntries);var modifiers=new List<ushort>();ushort key=0;foreach(string raw in parts){string s=raw.Trim();if(EqualsAny(s,"Ctrl","Control","LCtrl","RCtrl"))AddUnique(modifiers,0x11);else if(EqualsAny(s,"Shift","LShift","RShift"))AddUnique(modifiers,0x10);else if(EqualsAny(s,"Alt","Menu","LAlt","RAlt"))AddUnique(modifiers,0x12);else if(EqualsAny(s,"Win","Windows","Cmd","LWin","RWin"))AddUnique(modifiers,0x5B);else{ushort parsed=ParseVirtualKeyCode(s);if(parsed!=0)key=parsed;}}var down=new List<NativeMethods.INPUT>();foreach(ushort m in modifiers)down.Add(CreateKeyInput(m,false));if(key!=0)down.Add(CreateKeyInput(key,false));if(down.Count>0)NativeMethods.SendInput((uint)down.Count,down.ToArray(),Marshal.SizeOf(typeof(NativeMethods.INPUT)));Thread.Sleep(Math.Max(5,holdMs));var up=new List<NativeMethods.INPUT>();if(key!=0)up.Add(CreateKeyInput(key,true));for(int i=modifiers.Count-1;i>=0;--i)up.Add(CreateKeyInput(modifiers[i],true));if(up.Count>0)NativeMethods.SendInput((uint)up.Count,up.ToArray(),Marshal.SizeOf(typeof(NativeMethods.INPUT)));}
        internal static void ExecuteTypeText(string text,int charDelayMs){if(string.IsNullOrEmpty(text))return;if(charDelayMs<=20){var inputs=new NativeMethods.INPUT[text.Length*2];for(int i=0;i<text.Length;i++){inputs[i*2]=NativeMethods.CreateUnicodeKeyInput(text[i],false);inputs[i*2+1]=NativeMethods.CreateUnicodeKeyInput(text[i],true);}NativeMethods.SendInput((uint)inputs.Length,inputs,Marshal.SizeOf(typeof(NativeMethods.INPUT)));return;}foreach(char c in text){var pair=new[]{NativeMethods.CreateUnicodeKeyInput(c,false),NativeMethods.CreateUnicodeKeyInput(c,true)};NativeMethods.SendInput(2,pair,Marshal.SizeOf(typeof(NativeMethods.INPUT)));Thread.Sleep(charDelayMs);}}
        internal static NativeMethods.INPUT CreateKeyInput(ushort vk,bool keyUp)=>NativeMethods.CreateVirtualKeyInput(vk,keyUp,IsExtendedKey(vk));
        internal static bool IsExtendedKey(ushort vk){switch(vk){case 0x21:case 0x22:case 0x23:case 0x24:case 0x25:case 0x26:case 0x27:case 0x28:case 0x2D:case 0x2E:case 0x5B:case 0x5C:case 0x6F:case 0x90:case 0xA3:case 0xA5:return true;default:return false;}}
        internal static ushort ParseVirtualKeyCode(string s){if(string.IsNullOrEmpty(s))return 0;if(string.Equals(s,"Space",StringComparison.OrdinalIgnoreCase))return 0x20;if(string.Equals(s,"Enter",StringComparison.OrdinalIgnoreCase)||string.Equals(s,"Return",StringComparison.OrdinalIgnoreCase))return 0x0D;if(string.Equals(s,"Esc",StringComparison.OrdinalIgnoreCase)||string.Equals(s,"Escape",StringComparison.OrdinalIgnoreCase))return 0x1B;if(string.Equals(s,"Tab",StringComparison.OrdinalIgnoreCase))return 0x09;if(string.Equals(s,"Backspace",StringComparison.OrdinalIgnoreCase)||string.Equals(s,"Back",StringComparison.OrdinalIgnoreCase))return 0x08;if(string.Equals(s,"Delete",StringComparison.OrdinalIgnoreCase)||string.Equals(s,"Del",StringComparison.OrdinalIgnoreCase))return 0x2E;if(string.Equals(s,"Insert",StringComparison.OrdinalIgnoreCase)||string.Equals(s,"Ins",StringComparison.OrdinalIgnoreCase))return 0x2D;if(string.Equals(s,"Home",StringComparison.OrdinalIgnoreCase))return 0x24;if(string.Equals(s,"End",StringComparison.OrdinalIgnoreCase))return 0x23;if(string.Equals(s,"PageUp",StringComparison.OrdinalIgnoreCase)||string.Equals(s,"PgUp",StringComparison.OrdinalIgnoreCase))return 0x21;if(string.Equals(s,"PageDown",StringComparison.OrdinalIgnoreCase)||string.Equals(s,"PgDn",StringComparison.OrdinalIgnoreCase))return 0x22;if(string.Equals(s,"Up",StringComparison.OrdinalIgnoreCase))return 0x26;if(string.Equals(s,"Down",StringComparison.OrdinalIgnoreCase))return 0x28;if(string.Equals(s,"Left",StringComparison.OrdinalIgnoreCase))return 0x25;if(string.Equals(s,"Right",StringComparison.OrdinalIgnoreCase))return 0x27;for(int i=1;i<=24;i++)if(string.Equals(s,"F"+i,StringComparison.OrdinalIgnoreCase))return(ushort)(0x70+i-1);for(int i=0;i<=9;i++)if(string.Equals(s,"Num"+i,StringComparison.OrdinalIgnoreCase)||string.Equals(s,"NumPad"+i,StringComparison.OrdinalIgnoreCase)||string.Equals(s,"Numpad"+i,StringComparison.OrdinalIgnoreCase))return(ushort)(0x60+i);if(s.Length==1){char c=char.ToUpperInvariant(s[0]);if((c>='A'&&c<='Z')||(c>='0'&&c<='9'))return c;}if(ushort.TryParse(s,out ushort numeric))return numeric;return 0;}
        private static bool EqualsAny(string value,params string[] choices){foreach(var x in choices)if(string.Equals(value,x,StringComparison.OrdinalIgnoreCase))return true;return false;} private static void AddUnique(List<ushort> list,ushort value){if(!list.Contains(value))list.Add(value);}
    }
}
